### ISSUE TITLE
wrong MIME type for js scripts on meet.primrosevr.com

### ISSUE THREAD

**Issue by jvns** [capnmidnight/lozya#19]
When I visit the example installation, I get a couple of errors in the JS console and it won't load the game.

> Loading module from “https://meet.primrosevr.com/scripts/game.js” was blocked because of a disallowed MIME type (“text/plain”).

```
$ curl -I https://meet.primrosevr.com/scripts/game.js  | grep content-type
content-type: text/plain; charset=utf-8
```

**Comment by capnmidnight** [comment]
Hrm, that's really weird. I didn't get this error as of yesterday, but I'm getting it now.

I'm using Azure CDN to host the front-end files. I had to look up how to change the MIME type of a file in Azure Blob Storage. All of the JS files were definitely set to "text/plain". I changed them to "text/javascript" just now. Still waiting to see the CDN update.

**Comment by capnmidnight** [comment]
It works right if I access the endpoint directly... ah, look at that, there's a Purge button. Let's see what that does.

**Comment by capnmidnight** [comment]
OK! Looks like it's good now. Thanks for the head's up.

**Comment by jvns** [comment]
thanks! Also thanks for writing such clear installation instructions -- they worked perfectly and I got my own instance set up super quickly.

**Comment by capnmidnight** [comment]
Awesome! Though honestly, most of the installation ease comes from the hard work the folks at 8x8 did on Jitsi. My overlay is so small it would be hard to obfuscate its installation without actively trying to.

If you don't mind, could you report back in a little while on how it's working out for you?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by capnmidnight** [comment]
BTW, I don't know if you noticed, and I forgot to mention it in the README before today, but index.html includes links to the Lozya repo *and* my Twitter profile. So you might want to change/remove that.
