### ISSUE TITLE
suitable tilesets

### ISSUE THREAD

**Issue by severak** [capnmidnight/lozya#2]
Hi,
I have gathered some suitable tilesets from itch.io:

- https://pipoya.itch.io/pipoya-rpg-tileset-32x32
- https://stealthix.itch.io/rpg-nature-tileset
- https://guttykreum.itch.io/field-of-green
- https://beast-pixels.itch.io/overworld-tileset-grass-biome (this is 16x16, but I really like it)

There are also some avatars available:

- https://pipoya.itch.io/pipoya-free-rpg-character-sprites-32x32

these are enemies, but seems to be usable too:

- https://pixel-frog.itch.io/pixel-adventure-1
- https://pixel-frog.itch.io/pixel-adventure-2

There is definitely lot of stuff to take from itch.io.

I think I can volunteer to add code which will make these live, but I am not sure how to test it without my own jitsi meet instance. It's possible to test it somehow from localhost?

**Comment by capnmidnight** [comment]
The current server is still setup to accept connections from local host. You just need a local, static webserver to host the files.

**Comment by capnmidnight** [comment]
Does anyone know if the CC-0 license is compatible with MIT? Jitsi Meet is Apache 2 license, so I might need to pull jitsihax.js out to a separately licensed project. But the front end code just used the Jitsi iframe API without modification, so I think we can keep MIT for the frontend code.

**Comment by capnmidnight** [comment]
@severak I just implemented basic tileset support, but haven't touched the tilesets you linked. Are you still interested in doing this?

**Comment by severak** [comment]
@capnmidnight I will definitely look into that.

**Comment by severak** [comment]
@capnmidnight implemented first of these tilesets in branch `custom_tiles`. I will look into some tooling as this manual editing of maps and tilesets is really tedious process.

There is [Tiled map editor](https://www.mapeditor.org/) which we should definitely use. But I am not sure how to convert images...

**Comment by capnmidnight** [comment]
This looks great! I'm going to merge it in now. Agreed on needing a map editor. I'll check out Tiled and see what the output format looks like.

**Comment by capnmidnight** [comment]
boom 405fd1506d5b4d3672e7a52e173f5ab292a5827e
